---
# Io doesn't report the correct version, so there's no way to tell what
# version is actually installed.
- name: Check if Io is installed
  command: which io
  register: io_installed
  ignore_errors: true

- name: Download the io x86 package
  get_url: url=http://iobin.suspended-chord.info/linux/iobin-linux-x86-deb-current.zip
           dest=/tmp/iobin.zip
  when: ansible_architecture == "i386" and io_installed|failed

- name: Download the io x64 package
  get_url: url=http://iobin.suspended-chord.info/linux/iobin-linux-x64-deb-current.zip
           dest=/tmp/iobin.zip
  when: ansible_architecture == "x86_64" and io_installed|failed

- name: Install unzip
  apt: pkg=unzip state=present

- name: Unzip the io package
  unarchive: src=/tmp/iobin.zip dest=/tmp
  when: io_installed|failed

- name: Install the io x86 package
  command: dpkg -i /tmp/IoLanguage-{{ io_version }}-Linux-x86.deb creates=/usr/local/bin/io
  when: ansible_architecture == "i386" and io_installed|failed

- name: Install the io x64 package
  command: dpkg -i /tmp/IoLanguage-{{ io_version }}-Linux-x64.deb creates=/usr/local/bin/io
  when: ansible_architecture == "x86_64" and io_installed|failed

- name: Clean up the Io package and archive
  file: path=/tmp/{{ item }} state=absent
  with_items:
    - iobin.zip
    - IoLanguage-{{ io_version }}-Linux-x86.deb
    - IoLanguage-{{ io_version }}-Linux-x64.deb
