---
- name: Check if RStudio is installed
  shell: rstudio-server version | grep {{ rstudio_version }}
  register: rstudio_installed
  ignore_errors: true

- name: Install RStudio's prerequisites
  apt: pkg={{ item }} state=installed
  with_items:
    - libapparmor1
    - libcurl4-gnutls-dev

- include: rstudio_install.yml
  when: rstudio_installed|failed

- name: Clean up the RStudio package
  file: path=/tmp/rstudio-{{ rstudio_version }}.deb state=absent

- include: rstudio_vagrant.yml
  when: interactive_user is defined and interactive_user == "vagrant"
