---
- name: Download 32-bit RStudio
  get_url: url=http://download2.rstudio.org/rstudio-server-{{ rstudio_version }}-i386.deb
           dest=/tmp/rstudio-{{ rstudio_version }}.deb
  when: ansible_architecture == "i386"

- name: Download 64-bit RStudio
  get_url: url=http://download2.rstudio.org/rstudio-server-{{ rstudio_version }}-amd64.deb
           dest=/tmp/rstudio-{{ rstudio_version }}.deb
  when: ansible_architecture == "x86_64"

- name: Install RStudio
  apt: deb=/tmp/rstudio-{{ rstudio_version }}.deb

