---
- name: Install the Brightbox PPA
  apt_repository: repo=ppa:brightbox/ruby-ng

- name: Install ruby 1.8
  apt: name=ruby1.8-full
  when: ruby_version == "1.8"

- name: Install ruby 1.9.3
  apt: name=ruby1.9.3
  when: ruby_version == "1.9.1"

- name: Install Ruby 2.0
  apt: name={{ item }}
  with_items:
    - ruby2.0
    - ruby2.0-dev
    - ruby2.0-doc
  when: ruby_version == "2.0"

- name: Install Ruby 2.1
  apt: name={{ item }}
  with_items:
    - ruby2.1
    - ruby2.1-dev
    - ruby2.1-doc
  when: ruby_version == "2.1"

- name: Install Ruby 2.2
  apt: name={{ item }}
  with_items:
    - ruby2.2
    - ruby2.2-dev
    - ruby2.2-doc
  when: ruby_version == "2.2"

