
---
- name: Download JRuby
  get_url: url=http://jruby.org.s3.amazonaws.com/downloads/{{ jruby_version }}/jruby-bin-{{ jruby_version }}.tar.gz
           dest=/tmp/jruby-{{ jruby_version }}.tar.gz

- name: Install JRuby
  unarchive: src=/tmp/jruby-{{ jruby_version }}.tar.gz dest=/opt/

- name: Add JRuby's bin directory to the system path
  template: src=jruby.sh.j2 dest=/etc/profile.d/jruby.sh

