---
- name: Add the sbt repository
  apt_repository: repo='deb http://dl.bintray.com/sbt/debian /' state=present

- name: Install sbt
  apt: name=sbt state=latest

- name: Force-download sbt's jars
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: sbt help creates=/home/{{ interactive_user }}/.sbt
  when: interactive_user is defined and initialize_sbt

