
---
- name: Download the sbt package
  get_url: url=http://dl.bintray.com/sbt/debian/sbt-{{ sbt_version }}.deb
           dest=/tmp/sbt-{{ sbt_version }}.deb
           owner=root group=root mode=0644

- name: Install sbt
  command: dpkg -i /tmp/sbt-{{ sbt_version }}.deb creates=/usr/bin/sbt

- name: Force-download sbt's jars
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: sbt help creates=/home/{{ interactive_user }}/.sbt
  when: interactive_user and initialize_sbt

