---
- name: Install prerequisitives for CouchDB
  apt: name={{ item }}
  with_items:
    - g++
    - libmozjs185-dev
    - libicu-dev
    - libcurl4-gnutls-dev
    - libtool

- name: Download CouchDB
  get_url: url={{ apache_mirror }}/couchdb/source/{{ couchdb_version }}/apache-couchdb-{{ couchdb_version }}.tar.gz
           dest=/tmp/couchdb-{{ couchdb_version }}.tar.gz

- name: Unpack CouchDB
  unarchive: src=/tmp/couchdb-{{ couchdb_version }}.tar.gz
             dest=/tmp/

- name: Configure CouchDB
  command: ./configure chdir=/tmp/apache-couchdb-{{ couchdb_version }} creates=/tmp/apache-couchdb-{{ couchdb_version }}/Makefile

- name: Build CouchDB from source
  command: make chdir=/tmp/apache-couchdb-{{ couchdb_version }} creates=/tmp/apache-couchdb-{{ couchdb_version }}/bin/couchdb

- name: Install CouchDB
  command: make install chdir=/tmp/apache-couchdb-{{ couchdb_version }}

- name: Clean up the CouchDB source and tarball
  file: path=/tmp/{{ item }} state=absent
  with_items:
    - couchdb-{{ couchdb_version }}.tar.gz
    - apache-couchdb-{{ couchdb_version }}

- name: Install CouchDB's scripts
  file: src=/usr/local/etc/{{ item }}/couchdb
        dest=/etc/{{ item }}/couchdb
        state=link
  with_items:
    - logrotate.d
    - init.d

- name: Add the 'couchdb' user
  user: name=couchdb home=/usr/local/var/lib/couchdb shell=/bin/sh
        system=yes state=present

- name: Ensure that CouchDB has permissions on its directories
  file: path=/usr/local/var/{{ item }}/couchdb state=directory
        recurse=yes owner=couchdb group=couchdb
  with_items:
    - log
    - lib
    - run

