---
- name: Check whether CouchDB is installed.
  shell: couchdb -V | grep "couchdb - Apache CouchDB {{ couchdb_version }}"
  register: couchdb_installed
  ignore_errors: true

- include: build_couchdb.yml
  when: couchdb_installed|failed and couchdb_source_install

- include: couchdb_ppa.yml
  when: couchdb_installed|failed and not couchdb_source_install

- name: Enable and start CouchDB.
  service: name=couchdb state=started enabled=yes
