---
- name: Add the Erlang Solutions APT key
  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present

- name: Add the Erlang Solutions APT repository
  apt_repository: repo='deb http://binaries.erlang-solutions.com/debian {{ ansible_distribution_release }} contrib' state=present

- name: Install the Erlang Solutions erlang packages (with hipe)
  apt: name={{ item }} state=present
  with_items:
    - erlang-base-hipe
    - erlang-nox
    - erlang-manpages
    - erlang-dev
  when: erlang_use_hipe

- name: Install the Erlang Solutions erlang packages (without hipe)
  apt: name={{ item }} state=present
  with_items:
    - erlang-base
    - erlang-nox
    - erlang-manpages
    - erlang-dev
  when: not erlang_use_hipe

- name: Install rebar
  get_url: url=https://github.com/rebar/rebar/wiki/rebar
           dest=/usr/local/bin/rebar
           owner=root group=root mode=0755

