---
- name: Install OpenJDK 7
  apt: pkg=openjdk-7-jdk state=present
       install_recommends=no

- name: Install leiningen
  get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein
           dest=/usr/local/bin/lein
           owner=root group=root mode=0755

- name: Force-download leiningen's jars
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: lein help creates=/home/{{ interactive_user }}/.lein"
  when: interactive_user and initialize_lein

- name: Download the sbt package
  get_url: url=http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/{{ sbt_version }}/sbt.deb
           dest=/tmp/sbt.deb
           owner=root group=root mode=0644

- name: Install sbt
  command: dpkg -i /tmp/sbt.deb creates=/usr/bin/sbt

- name: Force-download sbt's jars
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: sbt help creates=/home/{{ interactive_user }}/.sbt
  when: interactive_user and initialize_sbt

- name: Download Maven
  get_url: url={{ apache_mirror }}/maven/maven-{{ maven_version[0] }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
           dest=/tmp/maven.tar.gz
  when: maven_version[0] == "3"

- name: Install Maven
  unarchive: src=/tmp/maven.tar.gz dest=/opt/

- name: Add Maven's bin directory to the system path
  template: src=maven.sh.j2 dest=/etc/profile.d/maven.sh

- name: Download Ant
  get_url: url={{ apache_mirror }}/ant/binaries/apache-ant-{{ ant_version }}-bin.tar.bz2
           dest=/tmp/ant.tar.bz2

- name: Install Ant
  unarchive: src=/tmp/ant.tar.bz2 dest=/opt/

- name: Add Ant's bin directory to the system path
  template: src=ant.sh.j2 dest=/etc/profile.d/ant.sh

- name: Download Gradle
  get_url: url=http://services.gradle.org/distributions/gradle-{{ gradle_version }}-all.zip
           dest=/tmp/gradle.zip

- name: Install Gradle
  unarchive: src=/tmp/gradle.zip dest=/opt/

- name: Add Gradle's bin directory to the system path
  template: src=gradle.sh.j2 dest=/etc/profile.d/gradle.sh

- name: Download Groovy
  get_url: url=http://dist.groovy.codehaus.org/distributions/groovy-binary-{{ groovy_version }}.zip
           dest=/tmp/groovy.zip

- name: Install Groovy
  unarchive: src=/tmp/groovy.zip dest=/opt/

- name: Add Groovy's bin directory to the system path
  template: src=groovy.sh.j2 dest=/etc/profile.d/groovy.sh

- name: Download JRuby
  get_url: url=http://jruby.org.s3.amazonaws.com/downloads/{{ jruby_version }}/jruby-bin-{{ jruby_version }}.tar.gz
           dest=/tmp/jruby.tar.gz

- name: Install JRuby
  unarchive: src=/tmp/jruby.tar.gz dest=/opt/

- name: Add JRuby's bin directory to the system path
  template: src=jruby.sh.j2 dest=/etc/profile.d/jruby.sh

# TODO: Split into individual tasks or roles
#
