---
- name: Add the Docker APT key
  apt_key: id=A88D21E9 url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD8576A8BA88D21E9

- name: Add the Docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Install the Docker package
  apt: name=lxc-docker state=present

- name: Start the Docker service
  service: name=docker state=started enabled=yes

