---
- name: Check if Maven is installed
  command: stat /opt/apache-maven-{{ maven_version }}/bin/mvn
  register: maven_installed
  ignore_errors: true

- include: install_maven.yml
  when: maven_installed|failed

- name: Add Maven's bin directory to the system path
  template: src=maven.sh.j2 dest=/etc/profile.d/maven.sh

- name: Check if Ant is installed
  command: stat /opt/apache-ant-{{ ant_version }}/bin/ant
  register: ant_installed
  ignore_errors: true

- include: install_ant.yml
  when: ant_installed|failed

- name: Add Ant's bin directory to the system path
  template: src=ant.sh.j2 dest=/etc/profile.d/ant.sh

- name: Check if Gradle is installed
  command: stat /opt/gradle-{{ gradle_version }}/bin/gradle
  register: gradle_installed
  ignore_errors: true

- include: install_gradle.yml
  when: gradle_installed|failed

- name: Add Gradle's bin directory to the system path
  template: src=gradle.sh.j2 dest=/etc/profile.d/gradle.sh

