
---
- name: Get the 32-bit Serf distribution
  get_url: url=https://dl.bintray.com/mitchellh/serf/{{ serf_version }}_linux_386.zip
           dest=/tmp/serf.zip
  when: ansible_architecture == "i386"

- name: Get the 64-bit Serf distribution
  get_url: url=https://dl.bintray.com/mitchellh/serf/{{ serf_version }}_linux_amd64.zip
           dest=/tmp/serf.zip
  when: ansible_architecture == "x86_64"

- name: Unpack the Serf distribution
  unarchive: src=/tmp/serf.zip dest=/usr/local/bin
