---
- name: Check if Serf is installed
  shell: /usr/local/bin/serf version | grep 'Serf v{{ serf_version }}'
  register: serf_installed
  ignore_errors: true

- name: Get the 32-bit Serf distribution
  get_url: url=https://dl.bintray.com/mitchellh/serf/{{ serf_version }}_linux_386.zip
           dest=/tmp/serf-{{ serf_version }}.zip
  when: ansible_architecture == "i386" and serf_installed|failed

- name: Get the 64-bit Serf distribution
  get_url: url=https://dl.bintray.com/mitchellh/serf/{{ serf_version }}_linux_amd64.zip
           dest=/tmp/serf-{{ serf_version }}.zip
  when: ansible_architecture == "x86_64" and serf_installed|failed

- name: Unpack the Serf distribution
  unarchive: src=/tmp/serf-{{ serf_version }}.zip dest=/usr/local/bin
  when: serf_installed|failed

- name: Clean up the Serf archive
  file: path=/tmp/serf-{{ serf_version }}.zip state=absent
