---
- name: Check if Vagrant is installed
  shell: /usr/bin/vagrant -v | grep 'Vagrant {{ vagrant_version }}'
  register: vagrant_installed
  ignore_errors: true

- name: Get the 32-bit Vagrant package
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vagrant_version }}_i686.deb
           dest=/tmp/vagrant-{{ vagrant_version }}.deb
  when: ansible_architecture == "i386" and vagrant_installed|failed

- name: Get the 64-bit Vagrant package
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vagrant_version }}_x86_64.deb
           dest=/tmp/vagrant-{{ vagrant_version }}.deb
  when: ansible_architecture == "x86_64" and vagrant_installed|failed

- name: Remove any existing Vagrant installation
  apt: name=vagrant state=absent
  when: vagrant_installed|failed

- name: Install the Vagrant package
  apt: deb=/tmp/vagrant-{{ vagrant_version }}.deb
  when: vagrant_installed|failed

- name: Clean up the Vagrant archive
  file: path=/tmp/vagrant-{{ vagrant_version }}.deb state=absent

