---
- name: Add the OPAM PPA
  apt_repository: repo="ppa:avsm/ppa"
  when: ansible_distribution_version|float <= 13.10

- name: Install the OPAM and Ocaml packages
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - build-essential
    - m4
    - opam
    - ocaml
    - ocaml-native-compilers

- name: Initialize OPAM
  sudo_user: "{{ interactive_user }}"
  sudo: True
  shell: opam init -a creates=/home/{{ interactive_user }}/.opam
  when: interactive_user and ocaml_initialize_opam
