---
- name: Add the OPAM PPA
  apt_repository: repo="ppa:avsm/ppa"
  when: ansible_distribution_version|version_compare("13.10", "<=")

- name: Install the OPAM and Ocaml packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - build-essential
    - m4
    - opam
    - ocaml
    - ocaml-native-compilers

- name: Initialize OPAM
  sudo_user: "{{ interactive_user }}"
  sudo: True
  shell: opam init -a creates=/home/{{ interactive_user }}/.opam
  when: interactive_user is defined and ocaml_initialize_opam

