---
- name: Add the Elasticsearch apt key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: Add the Elasticsearch repository
  apt_repository: repo="deb http://packages.elastic.co/elasticsearch/{{ elasticsearch_version }}/debian stable main"

- name: Install Elasticsearch
  apt: name=elasticsearch state=installed

- name: Enable and start the Elasticsearch service
  service: name=elasticsearch enabled=yes state=started

