---
- name: Check to see if Anaconda is installed
  command: stat /home/{{ interactive_user }}/.python/bin/python
  register: anaconda_installed
  ignore_errors: true
  when: interactive_user is defined

- include: install_anaconda.yml
  when: interactive_user is defined and not anaconda_installed

- name: Uninstall Anaconda's cURL
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: /home/{{ interactive_user }}/.python/bin/conda remove --yes -q curl
  when: interactive_user is defined and full_anaconda

- name: Clean up Anaconda's installer
  file: path=/tmp/Miniconda-Linux.sh state=absent

- name: Install pythonpy
  pip: name=pythonpy executable=/home/{{ interactive_user }}/.python/bin/pip state=present
  when: interactive_user is defined

- name: Add the PyPy PPA
  apt_repository: repo=ppa:pypy/ppa state=present

- name: Install the PyPy package
  apt: name=pypy state=present

# TODO: Configure IPython to serve notebooks out of /vagrant

