---
- name: Download Anaconda (32-bit)
  get_url: url=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86.sh
           dest=/tmp/Miniconda-Linux.sh
           owner=root group=root owner=0755
  when: ansible_architecture == "i386" and interactive_user != false

- name: Download Anaconda (64-bit)
  get_url: url=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh
           dest=/tmp/Miniconda-Linux.sh
           owner=root group=root owner=0755
  when: ansible_architecture == "x86_64" and interactive_user != false

- name: Install Anaconda
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: bash /tmp/Miniconda-Linux.sh -b -p /home/{{ interactive_user }}/.python creates=/home/{{ interactive_user }}/.python
  when: interactive_user != false

- name: Update Anaconda
  sudo: True
  sudo_user: "{{ interactive_user }}"
  command: /home/{{ interactive_user }}/.python/bin/conda update --yes -q conda
  when: interactive_user != false

- name: Add the PyPy PPA
  apt_repository: repo=ppa:pypy/ppa state=present

- name: Install the PyPy package
  apt: pkg=pypy state=present

# TODO: Install pip by default
# TODO: Install IPython and configure to serve notebooks out of /vagrant

