---
- name: Install the Julia PPA
  apt_repository: repo=ppa:staticfloat/juliareleases state=present

- name: Install the Julia packages
  apt: name=julia state=latest

# TODO: Add an option for nightlies
# TODO: IJulia

